export type FreeService = {
  slug: string
  title: string
  subtitle: string
  description: string
  href: string
  category: "free" | "paid"
}

export const FREE_ASTROLOGY_SERVICES: FreeService[] = [
  {
    slug: "online-kundli",
    title: "Kundli (Birth Chart)",
    subtitle: "online kundli free",
    description: "Generate your Janam Kundli using birth details and accurate calculations.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "horoscope-matching",
    title: "Horoscope Matching",
    subtitle: "horoscope matching, kundali milan",
    description: "Check compatibility with traditional matching factors.",
    href: "/matching",
    category: "free",
  },
  {
    slug: "astrosage-matrimony",
    title: "AstroSage Matrimony",
    subtitle: "Free matrimony - shaadi",
    description: "Explore spiritually aligned matchmaking services.",
    href: "/services/astrosage-matrimony",
    category: "free",
  },
  {
    slug: "ask-question",
    title: "Ask a Question",
    subtitle: "Ask a Question",
    description: "Ask astrology questions and get personalized guidance.",
    href: "/consultations",
    category: "free",
  },
  {
    slug: "dhruv-astro-software",
    title: "Dhruv Astro Software",
    subtitle: "Astro Dhruv Software",
    description: "Astrology software utilities and learning tools.",
    href: "/services/dhruv-astro-software",
    category: "free",
  },
  {
    slug: "career-counselling",
    title: "Career Counselling",
    subtitle: "Career Counselling",
    description: "Get career direction using horoscope analysis.",
    href: "/services/career-counselling",
    category: "free",
  },
  {
    slug: "brihat-kundli",
    title: "Brihat Kundli",
    subtitle: "Brihat Kundli",
    description: "Detailed Kundli insights across divisional charts.",
    href: "/services/brihat-kundli",
    category: "free",
  },
  {
    slug: "exam-results",
    title: "Exam Results",
    subtitle: "Exam Results",
    description: "Astrology guidance for education and exam outcomes.",
    href: "/services/exam-results",
    category: "free",
  },
  {
    slug: "talk-to-astrologer",
    title: "Talk to Astrologer",
    subtitle: "TALK TO THE BEST ASTROLOGERS IN INDIA",
    description: "Connect with astrologers through consultation services.",
    href: "/consultations",
    category: "paid",
  },
  {
    slug: "paid-services",
    title: "Paid Services",
    subtitle: "All about our paid services",
    description: "Explore premium astrology and spiritual services.",
    href: "/services/paid-services",
    category: "paid",
  },
  {
    slug: "horoscope-2026",
    title: "Horoscope 2026",
    subtitle: "Get Free horoscope 2026",
    description: "Yearly predictions for all zodiac signs.",
    href: "/horoscope",
    category: "free",
  },
  {
    slug: "lal-kitab-horoscope",
    title: "Lal Kitab Horoscope",
    subtitle: "free lal kitab remedies",
    description: "Lal Kitab based remedies and predictions.",
    href: "/services/lal-kitab-horoscope",
    category: "free",
  },
  {
    slug: "sade-sati-life-report",
    title: "Sade Sati Life Report",
    subtitle: "free sade sati report",
    description: "Understand Saturn cycles and practical remedies.",
    href: "/services/sade-sati-life-report",
    category: "free",
  },
  {
    slug: "year-analysis-varshphal",
    title: "Year Analysis (Varshphal)",
    subtitle: "your annual horoscope absolutely free",
    description: "Detailed annual analysis based on Varshphal principles.",
    href: "/services/year-analysis-varshphal",
    category: "free",
  },
  {
    slug: "baby-name-suggestion",
    title: "Baby Name Suggestion",
    subtitle: "get baby name suggestion free",
    description: "Get name suggestions aligned with birth data and nakshatra.",
    href: "/services/baby-name-suggestion",
    category: "free",
  },
  {
    slug: "gochar-phal-transit",
    title: "Gochar Phal (Transit Report)",
    subtitle: "get transit report",
    description: "Track planetary transits and their effects.",
    href: "/services/gochar-phal-transit",
    category: "free",
  },
  {
    slug: "life-report",
    title: "Life Report",
    subtitle: "get your life report free",
    description: "Comprehensive life report from core chart indicators.",
    href: "/services/life-report",
    category: "free",
  },
  {
    slug: "online-astrology-software",
    title: "Online Astrology Software",
    subtitle: "free astrology software",
    description: "Use astrology tools directly in your browser.",
    href: "/services/online-astrology-software",
    category: "free",
  },
  {
    slug: "hindi-kundli",
    title: "Hindi Kundli",
    subtitle: "free hindi kundli",
    description: "Generate Kundli reports in Hindi language format.",
    href: "/services/hindi-kundli",
    category: "free",
  },
  {
    slug: "numerology-calculator",
    title: "Numerology Calculator",
    subtitle: "free numerology calculator",
    description: "Calculate and interpret your numerology numbers.",
    href: "/services/numerology-calculator",
    category: "free",
  },
  {
    slug: "celebrity-horoscope",
    title: "Celebrity Horoscope",
    subtitle: "know about your celebrity horoscope",
    description: "Explore celebrity charts and astrology breakdowns.",
    href: "/services/celebrity-horoscope",
    category: "free",
  },
  {
    slug: "learn-astrology",
    title: "Learn Astrology",
    subtitle: "about vedic astrology",
    description: "Learn core Vedic astrology concepts and methods.",
    href: "/blog",
    category: "free",
  },
  {
    slug: "love-horoscope",
    title: "Love Horoscope",
    subtitle: "get your love horoscope absolutely free",
    description: "Relationship predictions from your horoscope.",
    href: "/horoscope",
    category: "free",
  },
  {
    slug: "gemstones-report",
    title: "Gemstones Report",
    subtitle: "know about your gemstones",
    description: "Find gemstone recommendations from chart analysis.",
    href: "/services/gemstones-report",
    category: "free",
  },
  {
    slug: "mangal-dosha",
    title: "Mangal Dosha",
    subtitle: "about your mangal dosha",
    description: "Check Mangal dosha and view practical remedies.",
    href: "/services/mangal-dosha",
    category: "free",
  },
  {
    slug: "dasha-phal-analysis",
    title: "Dasha Phal Analysis",
    subtitle: "free dasa phal analysis",
    description: "Analyze Mahadasha and Antardasha influences.",
    href: "/services/dasha-phal-analysis",
    category: "free",
  },
  {
    slug: "ascendant-calculator",
    title: "Ascendant Calculator",
    subtitle: "get ascendant calculator",
    description: "Find your Lagna (ascendant) accurately.",
    href: "/services/ascendant-calculator",
    category: "free",
  },
  {
    slug: "todays-rahukaal",
    title: "Today's Rahukaal",
    subtitle: "Get Today's Rahukalam - City Specific Local Rahu Kaal",
    description: "View city-specific Rahukaal timings for today.",
    href: "/panchang",
    category: "free",
  },
  {
    slug: "astrosage-tv",
    title: "AstroSage TV",
    subtitle: "Get free AstroSage TV",
    description: "Spiritual and astrology media content.",
    href: "/services/astrosage-tv",
    category: "free",
  },
  {
    slug: "occult-directory",
    title: "Occult Directory",
    subtitle: "Get astrologer",
    description: "Browse astrologers and occult practitioners.",
    href: "/consultations",
    category: "paid",
  },
  {
    slug: "chinese-astrology",
    title: "Chinese Astrology",
    subtitle: "Get chinese astrology",
    description: "Explore Chinese astrology signs and trends.",
    href: "/services/chinese-astrology",
    category: "free",
  },
  {
    slug: "kaalsarp-dosha",
    title: "Kaalsarp Dosha",
    subtitle: "Get Kaal Sarp Dosha",
    description: "Check Kaalsarp dosha and related remedies.",
    href: "/services/kaalsarp-dosha",
    category: "free",
  },
]

export const SERVICE_BY_SLUG = FREE_ASTROLOGY_SERVICES.reduce<Record<string, FreeService>>((acc, service) => {
  acc[service.slug] = service
  return acc
}, {})
