export type FreeService = {
  slug: string
  title: string
  subtitle: string
  description: string
  href: string
  category: "free" | "paid"
}

export const FREE_ASTROLOGY_SERVICES: FreeService[] = [
  {
    slug: "online-kundli",
    title: "Kundli (Birth Chart)",
    subtitle: "Online Kundli Generator",
    description: "Generate your Janam Kundli using birth details and Swiss-Ephemeris based calculations.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "moon-sign-calculator",
    title: "Moon Sign Calculator",
    subtitle: "Lunar Position Analysis",
    description: "Find your Moon sign and Nakshatra from birth details using exact planetary computations.",
    href: "/astro-tools?tool=moon-sign",
    category: "free",
  },
  {
    slug: "nakshatra-calculator",
    title: "Nakshatra Calculator",
    subtitle: "Birth Star Finder",
    description: "Discover your birth Nakshatra and Pada from your chart.",
    href: "/astro-tools?tool=nakshatra",
    category: "free",
  },
  {
    slug: "lagna-navamsa",
    title: "Lagna / Navamsa",
    subtitle: "Ascendant & D9 Analysis",
    description: "Calculate your ascendant (Lagna) in D1 and D9 Navamsa charts.",
    href: "/astro-tools?tool=lagna-navamsa",
    category: "free",
  },
  {
    slug: "rahu-ketu-calculator",
    title: "Rahu Ketu Calculator",
    subtitle: "Lunar Node Positions",
    description: "Find Rahu and Ketu positions in your birth chart with house placement.",
    href: "/astro-tools?tool=rahu-ketu",
    category: "free",
  },
  {
    slug: "sade-sati-check",
    title: "Sade Sati Check",
    subtitle: "Saturn Cycle Detector",
    description: "Determine if you are currently in Sade Sati period and get remedies.",
    href: "/astro-tools?tool=sade-sati",
    category: "free",
  },
  {
    slug: "lal-kitab-calculator",
    title: "Lal Kitab Calculator",
    subtitle: "Traditional Remedies",
    description: "Get Lal Kitab-based remedial suggestions from your birth chart.",
    href: "/astro-tools?tool=lal-kitab",
    category: "free",
  },
  {
    slug: "brihat-kundli",
    title: "Brihat Kundli",
    subtitle: "Detailed Chart Analysis",
    description: "Get detailed divisional chart insights, yogas, doshas, dasha periods, and remedies from your generated Kundli.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "mangal-dosha",
    title: "Mangal Dosha Check",
    subtitle: "Kuja Dosha Analysis",
    description: "Detect Mangal Dosha from your birth chart with severity and remedy guidance in your Kundli report.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "kaalsarp-dosha",
    title: "Kaalsarp Dosha Check",
    subtitle: "Rahu-Ketu Axis Analysis",
    description: "Analyze Kaalsarp influence and suggested corrective actions from your computed chart.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "dasha-phal-analysis",
    title: "Dasha Phal Analysis",
    subtitle: "Mahadasha & Antardasha",
    description: "View current and upcoming dasha periods with effect summaries and timing context.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "ascendant-calculator",
    title: "Ascendant Calculator",
    subtitle: "Lagna Finder",
    description: "Find your ascendant (Lagna) from exact birth date, time, and location inputs.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "life-report",
    title: "Life Report",
    subtitle: "Comprehensive Life Insights",
    description: "Get a consolidated life trend report across personality, career, relationships, and spirituality.",
    href: "/kundali",
    category: "free",
  },
  {
    slug: "horoscope-matching",
    title: "Kundli Milan (Guna Milan)",
    subtitle: "Ashtakoot Compatibility",
    description: "Compute 36-guna compatibility with detailed koot scores and Manglik parity from both birth charts.",
    href: "/kundli-matching",
    category: "free",
  },
  {
    slug: "numerology-report",
    title: "Numerology Report",
    subtitle: "Life Path & Destiny Numbers",
    description: "Get Life Path, Destiny, Personal Year, and Lo-Shu Grid analysis with lucky color and vehicle number.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "destiny-number",
    title: "Destiny Number",
    subtitle: "Numerological Destiny",
    description: "Calculate your Destiny Number from your name for life direction insights.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "personal-year",
    title: "Personal Year",
    subtitle: "Annual Numerological Cycle",
    description: "Find your Personal Year number and its meaning for annual planning.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "lo-shu-grid",
    title: "Lo-Shu Grid",
    subtitle: "Ancient Numerology Grid",
    description: "Analyze your Lo-Shu Grid from birth date for personality insights.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "lucky-color",
    title: "Lucky Color",
    subtitle: "Color Numerology",
    description: "Discover your lucky color based on numerological calculations.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "baby-name-finder",
    title: "Baby Name Finder",
    subtitle: "Numerology Name Suggestions",
    description: "Get baby name suggestions and lucky initials based on numerology.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "lucky-vehicle-number",
    title: "Lucky Vehicle Number",
    subtitle: "Vehicle Registration Numerology",
    description: "Find lucky vehicle registration numbers based on your numerology profile.",
    href: "/numerology",
    category: "free",
  },
  {
    slug: "flames-calculator",
    title: "FLAMES Calculator",
    subtitle: "Name-Based Love Prediction",
    description: "Check love compatibility using the FLAMES method (Friends, Love, Affection, Marriage, Enemies, Soulmates).",
    href: "/love-fun",
    category: "free",
  },
  {
    slug: "love-calculator",
    title: "Love Calculator",
    subtitle: "Compatibility Score & Guidance",
    description: "Calculate love compatibility with optional Kundli Milan when birth details are available.",
    href: "/love-fun",
    category: "free",
  },
  {
    slug: "daily-horoscope",
    title: "Daily Horoscope",
    subtitle: "Panchang-Based Daily Guidance",
    description: "Read daily sign-wise guidance generated using Panchang context, sign profile, and transit-aware signals.",
    href: "/horoscope",
    category: "free",
  },
  {
    slug: "personalized-horoscope",
    title: "Personalized Horoscope",
    subtitle: "Birth Details Based Reading",
    description: "Generate personalized daily guidance using birth date, birth time, birthplace, Moon sign, Nakshatra, and Panchang.",
    href: "/horoscope",
    category: "free",
  },
  {
    slug: "love-horoscope",
    title: "Love Horoscope",
    subtitle: "Relationship-Focused Daily Forecast",
    description: "View compatibility-oriented and relationship guidance from daily horoscope calculations.",
    href: "/horoscope",
    category: "free",
  },
  {
    slug: "todays-rahukaal",
    title: "Today's Rahukaal & Panchang",
    subtitle: "City-Specific Muhurat Windows",
    description: "Compute city-specific Rahukaal, Yamaganda, Gulika, and full Panchang windows for any date.",
    href: "/panchang",
    category: "free",
  },
]

export const SERVICE_BY_SLUG = FREE_ASTROLOGY_SERVICES.reduce<Record<string, FreeService>>((acc, service) => {
  acc[service.slug] = service
  return acc
}, {})
